language: groovy
sudo: false
cache:
  directories:
    - $HOME/.gradle
notifications:
  email: false
jdk:
  - oraclejdk8
script: gradle clean check
after_script:
- rm -rf libs/
- find ~/.gradle -type f -atime +30 -delete
- find ~/.gradle -type d -mindepth 1 -empty -delete